name: Check

on:
  push:
    branches:
      - "release/**"
      - "releases/**"
      - "feat/**"
      - "feature/**"
      - "fix/**"
      - "hotfix/**"
      - "chore/**"
      - "test/**"
      - "unit/**"
      - "perf/**"
      - "refactor/**"
      - "main"
env:
  FOUNDRY_PROFILE: ci

jobs:
  test:
    strategy:
      fail-fast: true
    name: Foundry Test
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@v3
        with:
          submodules: recursive

      - uses: actions/setup-node@v2
        with:
          node-version: "16.16.0"

      - name: Yarn
        run: |
          yarn

      - name: Install Foundry
        uses: foundry-rs/foundry-toolchain@v1
        with:
          version: nightly

      - name: Run Forge build
        run: |
          forge --version
          forge build --sizes
        id: build

      - name: Run Forge tests
        run: |
          forge test -vvv
        id: test
  analyze:
    name: Slither Analyze
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@v3
      - name: Run Slither
        # TODO: change to release version after it is bug free, ref: https://github.com/crytic/slither-action/pull/50
        uses: crytic/slither-action@dev
        with:
          node-version: 16.16.0 # should match .nvmrc or whatever your project required
          target: "./"
          slither-config: ./slither.config.json
          slither-version: 0.9.2
          solc-version: 0.8.18
          # https://github.com/crytic/slither/issues/1408
          slither-args: --exclude-dependencies --exclude-optimization --exclude-informational --exclude-low --exclude-medium --no-fail-pedantic --fail-high
